stages:
  - unit-test
  - build
  - integration-test
  - deploy-dev
  - deploy-prod

default:
  image: registry.gitlab.com/antoinecampbell/docker-images/build

test:
  stage: unit-test
  script:
    - cd node-functions
    - yarn install
    - yarn test
    - yarn sonar
  artifacts:
    reports:
      junit:
        - node-functions/build/junit.xml
  cache:
    key: ${CI_JOB_NAME}
    policy: pull-push
    paths:
      - node-functions/node_modules/

build:
  stage: build
  script:
    - cd node-functions
    - yarn build-zip
  artifacts:
    expire_in: 7 days
    paths:
      - node-functions/lambda.zip
  cache:
    key: ${CI_JOB_NAME}
    policy: pull-push
    paths:
      - node-functions/node_modules/

integration-test:
  stage: integration-test
  dependencies:
    - build
  environment:
    name: test
  variables:
    TF_VAR_environment: ${CI_COMMIT_SHORT_SHA}
  script:
    - cd $CI_PROJECT_DIR/terraform/resources
    - terraform init
    - terraform apply -auto-approve
    - export TABLE_NAME=$(terraform output -raw notes_table_name)
    - export BASE_URI=$(terraform output -raw api_url)
    - cd $CI_PROJECT_DIR/integration-tests
    - ./gradlew test
  after_script:
    - cd $CI_PROJECT_DIR/terraform/resources
    - terraform destroy -auto-approve
  artifacts:
    expire_in: 7 days
    name: terraform-state
    paths:
      - terraform/resources/terraform.tfstate
    reports:
      junit:
        - integration-tests/build/test-results/test/*.xml

deploy-dev:
  stage: deploy-dev
  environment:
    name: dev
  dependencies:
    - build
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/terraform
    TF_HTTP_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/dev
    TF_HTTP_USERNAME: gitlab-ci-token
    TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
    TF_VAR_environment: ${CI_ENVIRONMENT_NAME}
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
  cache:
    key: ${CI_JOB_NAME}
    policy: pull-push
    paths:
      - ${TF_ROOT}/.terraform