stages:
  - test
  - build
  - deploy-dev
  - deploy-prod

default:
  image: registry.gitlab.com/antoinecampbell/aws-serverless-infrastructure/build

test:
  stage: test
  script:
    - cd node-functions/notes
    - yarn install
    - yarn test
    - yarn sonar
  cache:
    key: "${CI_JOB_NAME}"
    policy: pull-push
    paths:
      - node-functions/notes/node_modules/

build:
  stage: build
  script:
    - cd node-functions/notes
    - yarn build-zip
  cache:
    key: "${CI_JOB_NAME}"
    policy: pull-push
    paths:
      - node-functions/notes/node_modules/